import os

REQUESTS_DIR = os.environ.get("REQUESTS_DIR", ".")
REQUESTS_FILENAME = os.environ["REQUESTS_FILENAME"]
RESULTS_ALL_FILENAME = os.environ.get("RESULTS_ALL_FILENAME", None)
RESULTS_FILENAME = os.environ.get("RESULTS_FILENAME", None)
