name: "Build"

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths-ignore:
      - "**.md"

  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.md"

defaults:
  run:
    shell: bash

env:
  IMAGE: "quay.io/fmperf/fmperf"
  IMAGE_REGISTRY: "quay.io"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Set up QEMU"
        uses: docker/setup-qemu-action@v3

      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v3

      - name: "Log in to container registry (release)"
        uses: docker/login-action@v3
        if: github.event_name != 'pull_request'
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ secrets.FMPERF_QUAY_USER }}
          password: ${{ secrets.FMPERF_QUAY_TOKEN }}

      - name: "Generate tags"
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.IMAGE }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,enable=true,priority=100,prefix=,suffix=,format=short     
            type=sha,enable=true,priority=100,prefix=${{ github.ref_name }}.,suffix=,format=short  

      - name: "Docker build release"
        uses: docker/build-push-action@v5
        with:
          context: .
          target: release
          build-args: |
            GIT_COMMIT_HASH=${{ github.sha }}
          tags: ${{ steps.meta.outputs.tags }}
          push: ${{ github.event_name != 'pull_request' }}
      
      - name: "List docker images"
        run: docker images

      - name: "Check disk usage"
        shell: bash
        run: |
          docker system df
          df -h
